export  const domElements = {
    desktopType: document.querySelector('.input_option'),
    desktopDescription: document.querySelector('.input_description'),
    desktopValue: document.querySelector('.input_amount'),
    overlayType : document.querySelector('.overlay_option'),
    overlayDescription:document.querySelector('.overlay_description'),
    overlayValue:document.querySelector('.overlay_amount'),
    addBtnDesktop: document.querySelector('.add'),
    incomeList: document.querySelector('.add-incomes_list'),
    expenseList:document.querySelector('.add-expenses_list'),
    addMobileButton: document.querySelector('.add_mobile_button'),
    overlayForm: document.querySelector('#overlay_form'),
    overlayFormAdd: document.querySelector('.overlay_add'),
    overlay:document.querySelector('.overlay'),
    errMsg: document.querySelector('.err_msg'),
    errMsgMobile: document.querySelector('.err_msg_mobile'),
    availableBalance: document.querySelector('.available_funds'),
    totalIncome:document.querySelector('.total__income'),
    totalExpense:document.querySelector('.total__expense'),
    totalPercentage: document.querySelector('.total__percentage'),
    main:document.querySelector('.main'),
    deleteBtn:document.querySelector('.add_remove'),
    percentages:document.querySelectorAll('.add_percentage'),
    date:document.querySelector('.date'),
    sign:document.querySelector('.sign'),
    settingsBody: document.querySelector('.settings_body'),
    settingsIcon: document.querySelector('.settings_icon'),
    settingsBodyContent: document.querySelector('.settings_body_content'),
    userCurrency: document.querySelector('.currency'),
    selectCurrency: document.querySelector('#currency'),
    notifications: document.querySelector('#notification'),
    notifyYes: document.querySelector('#notifyYes'),
    notifyNo: document.querySelector('#notifyNo')
}