export  const domElements = {
    desktopType: '.input_option',
    desktopDescription: '.input_description',
    desktopValue: '.input_amount',
    overlayType : '.overlay_option',
    overlayDescription:'.overlay_description',
    overlayValue:'.overlay_amount',
    addBtnDesktop: '.add',
    incomeList: '.add-incomes_list',
    expenseList:'.add-expenses_list',
    addMobileButton: '.add_mobile_button',
    overlayForm: '#overlay_form',
    overlayFormAdd: '.overlay_add',
    overlay:'.overlay',
    errMsg: '.err_msg',
    errMsgMobile: '.err_msg_mobile',
    availableBalance: '.available_funds',
    totalIncome:'.total__income',
    totalExpense:'.total__expense',
    totalPercentage: '.total__percentage',
    main:'.main',
    deleteBtn:'.add_remove',
    percentage:'.add_percentage',
    date:'.date',
    sign:'.sign',
    settingsBody: '.settings_body',
    settingsIcon: '.settings_icon',
    settingsBodyContent: '.settings_body_content',
    userCurrency: '.currency',
    selectCurrency: '#currency'
}